# Generated by Django 4.2.6 on 2023-10-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tipe',
            field=models.CharField(choices=[('hamburguesa', 'Hamburguesa'), ('acompañamiento', 'Acompañamiento')], max_length=200),
        ),
    ]
